[tool.black]
line-length = 100
target-version = ["py311"]
include = '\\.pyi?$'
exclude = '''
/(
  build
| dist
| venv
| \.venv
)/
'''

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["src"]
skip = ["build", "dist", "venv", ".venv"]

[tool.flake8]
max-line-length = 100
ignore = ["E203", "W503"]
exclude = ["build", "dist", "venv", ".venv"]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-q"
testpaths = ["tests"]
filterwarnings = [
  "ignore::DeprecationWarning",
]
