name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ '**' ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.11', '3.12' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies (base)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/base.txt

      - name: Install dependencies (models)
        run: |
          pip install -r requirements/models.txt

      - name: Install dependencies (vision)
        run: |
          pip install -r requirements/vision.txt

      - name: Install dependencies (dev)
        run: |
          pip install -r requirements/dev.txt

      - name: Lint (black)
        run: |
          black --check src tests

      - name: Lint (isort)
        run: |
          isort --profile black --check-only src tests

      - name: Lint (flake8)
        run: |
          flake8 src tests

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest -q

      - name: Save lockfile (pip freeze)
        if: ${{ matrix.python-version == '3.11' }}
        run: |
          pip freeze > requirements/lock-py311.txt

      - name: Upload lockfile artifact
        if: ${{ matrix.python-version == '3.11' }}
        uses: actions/upload-artifact@v4
        with:
          name: requirements-lock-py311
          path: requirements/lock-py311.txt


